version: '3'

services:
  postgres:
    image: postgres:11.2-alpine
    ports:
      - 5433:5432
    expose:
      - 5433
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
      - ./sql:/docker-entrypoint-initdb.d
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres

  backend:
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - postgres
    expose:
      - 4567
    ports:
      - 4567:4567
    working_dir: /app
    volumes:
      - .:/app
    command: >
      bash -c "chmod +x wait-for-it.sh && ./wait-for-it.sh -t 60 postgres:5432
      && (rake db:setup || rails db:create || rake db:migrate) 
      && rails server --binding 0.0.0.0 --port 4567"

